---
abstract: "cron as it should be. Or shouldn't? L<Please vote!|http://www.kohts.com/cron-5/vote/>"
author:
  - 'Petya Kohts <petya@kohts.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: snaked
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: 0
  Schedule::Cron::Events: 0
  Set::Crontab: 0
  Storable: 0
  Time::HiRes: 0
  Time::Local: 0
  Yandex::Tools: 0
version: 0.14
